# Generated by Django 3.2.14 on 2022-07-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='Query',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
